{
 "title": "Yarnd",
 "description": "Dashboard for Yarn.social pods",
 "tags": [
  "dashboard",
  "je"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(yarnd_server_info, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(yarnd_server_info{job =~ '$job'}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Standard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "How long je has been up for",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yarnd_server_uptime{job=\"$job\", instance=\"$instance\"} / 1e6"
    }
   ]
  },
  {
   "title": "Twts Cached",
   "type": "stat",
   "description": "Number of Twts Cached",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yarnd_cache_twts{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Processing Time",
   "type": "stat",
   "description": "Feed Cache Processing Time",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yarnd_cache_feed_fetch_duration_seconds{job=\"$job\", instance=\"$instance\", quantile=\"0.95\"}"
    }
   ]
  },
  {
   "title": "Daily Active Users",
   "type": "stat",
   "description": "Daily Active Users (DAU)",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yarnd_server_dau{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "CPU Usage (%)",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]) * 100)",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Memory Usage",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "rss"
    }
   ]
  },
  {
   "title": "Feeds Cached",
   "type": "stat",
   "description": "Number of Feeds Cached",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yarnd_cache_feeds{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Queued",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yarnd_cache_feed_queue_latency_seconds{job=\"$job\", instance=\"$instance\", quantile=\"0.95\"}"
    }
   ]
  },
  {
   "title": "Sched",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yarnd_cache_feed_schedule_latency_seconds{job=\"$job\", instance=\"$instance\", quantile=\"0.95\"}"
    }
   ]
  },
  {
   "title": "Monthly Active Users",
   "type": "stat",
   "description": "Monthly Active Users (MAU)",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yarnd_server_mau{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "timeseries",
   "description": "Cache and Archive perf (such as cache last processing time in seconds and rate of archival)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "yarnd_cache_feed_fetch_duration_seconds{job=\"$job\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "processed"
    },
    {
     "expr": "yarnd_cache_last_convergence_seconds{job=\"$job\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "convergence"
    },
    {
     "expr": "increase(yarnd_cache_limited{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "limited"
    },
    {
     "expr": "increase(yarnd_cache_missing_twts{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "missing_twts"
    },
    {
     "expr": "increase(yarnd_cache_corrected_twts{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "corrected_twts"
    },
    {
     "expr": "yarnd_cache_feed_queue_latency_seconds{job=\"$job\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "queued"
    },
    {
     "expr": "yarnd_cache_feed_schedule_latency_seconds{job=\"$job\", instance=\"$instance\", quantile=\"0.95\"}",
     "legendFormat": "scheduling"
    },
    {
     "expr": "increase(yarnd_cache_queue_full{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "full"
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "timeseries",
   "description": "Database / Cache Stats (such as no. of users, feeds, sessions, cache size, etc)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "yarnd_db_feeds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "db_feeds"
    },
    {
     "expr": "yarnd_db_sessions{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "db_sessions"
    },
    {
     "expr": "yarnd_db_users{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "db_users"
    },
    {
     "expr": "yarnd_cache_feeds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "cached_feeds"
    },
    {
     "expr": "yarnd_cache_twts{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "cached_twts"
    },
    {
     "expr": "yarnd_feed_sources{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "feed_sources"
    },
    {
     "expr": "yarnd_server_sessions{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "server_sessions"
    },
    {
     "expr": "yarnd_server_dau{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "dau"
    },
    {
     "expr": "yarnd_server_mau{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "mau"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of process",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]) * 100)",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of process (resident, virtual)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "vm"
    }
   ]
  },
  {
   "title": "Go Memory",
   "type": "timeseries",
   "description": "Memory usage as sen by Go runtime",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "heap"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "mcache"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "mspan"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "other"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "stack"
    },
    {
     "expr": "go_memstats_sys_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "sys"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "timeseries",
   "description": "Memory allocations (bytes, heap, stack)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "heap"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "stack"
    }
   ]
  },
  {
   "title": "Threads / Goroutines",
   "type": "timeseries",
   "description": "Active threads / goroutines",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_threads{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "threads"
    },
    {
     "expr": "go_goroutines{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Garbage Collection duration",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(go_gc_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[$__rate_interval]) / irate(go_gc_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "avg"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", instance=\"$instance\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", instance=\"$instance\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    }
   ]
  },
  { "title": "HTTP Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Requte rate (saturation) by handler",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(\n    rate(yarnd_http_request_duration_seconds_count[$__rate_interval])\n) by (handler)",
     "legendFormat": "{{ handler }} req/s"
    }
   ]
  },
  {
   "title": "Handler Latency",
   "type": "timeseries",
   "description": "Latency (p95) by handler",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n    sum(\n        rate(yarnd_http_request_duration_seconds_bucket[$__rate_interval])\n    ) by (handler, le)\n)\n",
     "legendFormat": "{{ handler }} p95"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "Requte error rate (overall)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "rate(yarnd_http_request_duration_seconds_count{code=~\"5..\"}[$__rate_interval])",
     "legendFormat": "{{ handler }} errors/s"
    }
   ]
  },
  {
   "title": "WebSub",
   "type": "timeseries",
   "description": "WebSub subscriber and subscription statistics",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "targets": [
    { "expr": "yarnd_websub_topics", "legendFormat": "topics" },
    { "expr": "yarnd_websub_subscribers", "legendFormat": "subscribers" },
    { "expr": "yarnd_websub_verified", "legendFormat": "verified" },
    { "expr": "yarnd_websub_subscriptions", "legendFormat": "subscriptions" },
    { "expr": "yarnd_websub_confirmed", "legendFormat": "confirmed" }
   ]
  }
 ]
}